declare var describe: any;
declare var test: any;
declare var expect: any;

import AIFunctions, { AIFunctionDeclarations } from "../AIFunctions";

describe("AIFunctions declarations", () => {
  const expectedNames = [
    "get_user_data",
    "set_user_language",
    "fetch_url",
    "api_request",
    "retrieve_owners",
    "isOwner",
    "fetch_user",
    "fetch_discord_user",
    "get_memories",
    "insert_memory",
    "fetch_ai_rules",
    "list_knowledge_sources",
    "search_knowledge",
    "get_knowledge_source",
    "end_conversation",
    "search_user_by_username",
    "search_user_by_username_discord",
    "update_user_data",
    "execute_query",
    "on_guild",
    "guild_info",
    "current_guild_info",
    "get_member_permissions",
    "get_member_roles",
    "list_guild_channels",
    "search_guild_channels",
    "get_channel_info",
    "get_current_channel_info",
    "create_guild_channel",
    "edit_guild_channel",
    "delete_guild_channel",
    "create_thread",
    "send_channel_message",
    "send_channel_embed",
    "set_channel_permissions",
    "kick_member",
    "send_dm",
    "edit_msg",
    "check_vip_status",
    "list_workspace_files",
    "read_workspace_file",
    "write_workspace_file",
    "append_workspace_file",
    "delete_workspace_entry",
    "move_workspace_entry",
    "create_workspace_directory",
    "download_to_workspace",
    "search_workspace_text",
    "workspace_file_info",
    "search_web",
    "attach_workspace_file",
    "execute_js_code",
    "execute_command",
    "remove_memories",
    "remove_memory",
    "send_email",
    "get_bot_statistics",
    "check_database_health",
    "get_worker_pool_status",
    "clear_translation_cache",
    "get_user_warnings",
    "get_warning_details",
    "appeal_warning",
    "get_pending_appeals",
    "review_appeal",
    "global_ban_user",
    "global_unban_user",
    "global_mute_user",
    "global_unmute_user",
    "get_global_ban_status",
    "get_global_mute_status",
    "create_support_ticket",
    "create_bug_report",
    "get_ticket_details",
    "get_user_tickets",
    "assign_ticket",
    "close_ticket",
    "add_ticket_message",
    "get_ticket_messages",
    "add_staff_note",
    "get_staff_notes",
    "update_staff_status",
    "get_staff_audit_log",
    "get_rpg_character",
    "get_rpg_inventory",
    "get_rpg_equipment",
    "get_rpg_session",
    "get_rpg_account_status",
    "get_filter_config",
    "get_filter_words",
    "get_filter_webhooks",
    "get_custom_responses",
    "get_custom_response",
    "search_custom_responses",
    "get_globalchat_config",
    "get_ai_monitor_config",
    "list_ai_monitor_cases",
    "get_ai_monitor_case",
    "get_command_list",
    "get_command_info",
    "search_commands",
    "get_bot_features",
    "get_staff_permissions",
    "is_staff",
    "get_user_staff_rank",
    "check_vip_expiration",
    "get_system_info",
    "list_project_files",
    "read_project_file_lines",
    "search_project_text",
    "project_file_info",
    "list_log_files",
    "read_log_file_lines",
    "tail_log_file",
    "search_logs",
    "github_list_repo_dir",
    "github_fetch_repo_file",
    "github_search_repo",
    "add_user_to_convo",
    "remove_user_from_convo",
    "generate_code",
    "get_current_datetime",
    "list_guild_roles",
    "get_role_info",
    "create_role",
    "edit_role",
    "delete_role",
    "add_role_to_member",
    "remove_role_from_member",
    "get_role_members",
    "list_guild_members",
    "search_guild_members",
    "get_member_info",
    "ban_member",
    "unban_member",
    "timeout_member",
    "remove_timeout_member",
    "set_member_nickname",
    "move_member_voice",
    "create_chat_session",
    "list_chat_sessions",
    "load_chat_session",
    "delete_chat_session",
    "save_chat_message",
    "compress_chat_context",
    "add_memory_to_graph",
    "get_memory_graph",
    "search_memory_graph",
    "set_slowmode",
    "search_messages",
    "list_invites",
    "create_invite",
    "list_webhooks",
    "create_webhook",
    "manage_thread",
    "manage_scheduled_event",
    "list_emojis",
    "list_stickers",
    "manage_pin",
    "manage_giveaway",
    "create_reminder",
    "check_local_model",
    "list_local_models",
  ];

  test("exposes every declared tool across the split domain modules, with no duplicates", () => {
    expect(AIFunctionDeclarations.map((d: any) => d.name).sort()).toEqual([...expectedNames].sort());
    expect(new Set(AIFunctionDeclarations.map((d: any) => d.name)).size).toBe(expectedNames.length);
  });

  test("every declaration has a name, description, and parameters object", () => {
    for (const decl of AIFunctionDeclarations as any[]) {
      expect(typeof decl.name).toBe("string");
      expect(decl.name.length).toBeGreaterThan(0);
      expect(typeof decl.description).toBe("string");
      expect(decl.description.length).toBeGreaterThan(0);
      expect(decl.parameters).toBeDefined();
      expect(decl.parameters.type).toBe("object");
    }
  });

  test("default export wraps every declaration as an OpenAI-style function tool", () => {
    expect(AIFunctions.length).toBe(expectedNames.length);
    for (const tool of AIFunctions) {
      expect(tool.type).toBe("function");
      expect(typeof tool.function.name).toBe("string");
    }
  });
});
